In [70]:
import pandas as pd
import requests

In [ ]:
url_energy = 'https://data.elexon.co.uk/bmrs/api/v1/datasets/FUELINST?format=json'
url_carbon = 'https://api.carbonintensity.org.uk/intensity/2024-01-01/2024-01-02'
url_weather_f = 'https://api.open-meteo.com/v1/forecast?latitude=51.5&longitude=-0.1&hourly=wind_speed_10m,temperature_2m,shortwave_radiation'

# url fo r
url_weather_archive = 'https://archive-api.open-meteo.com/v1/archive?latitude=51.5&longitude=-0.1&start_date=2025-01-01&end_date=2025-12-31&hourly=temperature_2m,wind_speed_10m,shortwave_radiation&models=era5'

In [72]:
# Carbon API data frame
carbon_data = requests.get(url_carbon).json()
carbon_data['data']

carbon_df = pd.json_normalize(carbon_data['data'])
carbon_df.head()

,from,to,intensity.forecast,intensity.actual,intensity.index
0,2023-12-31T23:30Z,2024-01-01T00:00Z,68,63,low
1,2024-01-01T00:00Z,2024-01-01T00:30Z,64,64,low
2,2024-01-01T00:30Z,2024-01-01T01:00Z,62,64,low
3,2024-01-01T01:00Z,2024-01-01T01:30Z,65,62,low
4,2024-01-01T01:30Z,2024-01-01T02:00Z,61,71,low

In [ ]:
# Energy data frame
energy_data = requests.get(url_energy).json()
energy_df = pd.json_normalize(energy_data['data'])
energy_df.head()

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
0,FUELINST,2026-03-09T15:40:00Z,2026-03-09T15:35:00Z,2026-03-09,32,BIOMASS,2881
1,FUELINST,2026-03-09T15:40:00Z,2026-03-09T15:35:00Z,2026-03-09,32,CCGT,18484
2,FUELINST,2026-03-09T15:40:00Z,2026-03-09T15:35:00Z,2026-03-09,32,COAL,0
3,FUELINST,2026-03-09T15:40:00Z,2026-03-09T15:35:00Z,2026-03-09,32,INTELEC,998
4,FUELINST,2026-03-09T15:40:00Z,2026-03-09T15:35:00Z,2026-03-09,32,INTEW,-41

In [ ]:
# Weather Forecast API data frame for London
# Location: London; latitude: 51.49288; longitude: -0.102874756,
weather_f_data = requests.get(url_weather_f).json()

weather_f_df = pd.DataFrame(weather_f_data["hourly"])

print(weather_f_df.head())

               time  wind_speed_10m  temperature_2m  shortwave_radiation
0  2026-03-09T00:00             4.7             8.2                  0.0
1  2026-03-09T01:00             5.8             8.2                  0.0
2  2026-03-09T02:00             4.7             7.8                  0.0
3  2026-03-09T03:00             3.2             8.1                  0.0
4  2026-03-09T04:00             4.0             8.1                  0.0

In [ ]:
# Weather ERA5 Archive API data frame: 2025 year sample
# Date: 2025-01-01 to 2025-12-31
# Location: London; latitude: 51.5; longitude: 0
# Endpoint additon for historical data: &models=era5

weather_a_data = requests.get(url_weather_archive).json()

weather_a_df = pd.DataFrame(weather_a_data["hourly"])

print(weather_a_df.head())

               time  temperature_2m  wind_speed_10m  shortwave_radiation
0  2025-01-01T00:00            11.7            38.1                  0.0
1  2025-01-01T01:00            11.8            37.7                  0.0
2  2025-01-01T02:00            11.9            37.7                  0.0
3  2025-01-01T03:00            11.8            37.9                  0.0
4  2025-01-01T04:00            11.7            38.2                  0.0