In [1]:
import pandas as pd

In [4]:
url = 'https://api.carbonintensity.org.uk/intensity/2024-01-01/2024-01-02'

In [12]:
carbon_intensity_df = pd.read_json(url)

In [38]:
carbon_intensity_df

                                                 data
0   {'from': '2023-12-31T23:30Z', 'to': '2024-01-0...
1   {'from': '2024-01-01T00:00Z', 'to': '2024-01-0...
2   {'from': '2024-01-01T00:30Z', 'to': '2024-01-0...
3   {'from': '2024-01-01T01:00Z', 'to': '2024-01-0...
4   {'from': '2024-01-01T01:30Z', 'to': '2024-01-0...
5   {'from': '2024-01-01T02:00Z', 'to': '2024-01-0...
6   {'from': '2024-01-01T02:30Z', 'to': '2024-01-0...
7   {'from': '2024-01-01T03:00Z', 'to': '2024-01-0...
8   {'from': '2024-01-01T03:30Z', 'to': '2024-01-0...
9   {'from': '2024-01-01T04:00Z', 'to': '2024-01-0...
10  {'from': '2024-01-01T04:30Z', 'to': '2024-01-0...
11  {'from': '2024-01-01T05:00Z', 'to': '2024-01-0...
12  {'from': '2024-01-01T05:30Z', 'to': '2024-01-0...
13  {'from': '2024-01-01T06:00Z', 'to': '2024-01-0...
14  {'from': '2024-01-01T06:30Z', 'to': '2024-01-0...
15  {'from': '2024-01-01T07:00Z', 'to': '2024-01-0...
16  {'from': '2024-01-01T07:30Z', 'to': '2024-01-0...
17  {'from': '2024-01-01T08:00Z', 'to': '2024-01-0...
18  {'from': '2024-01-01T08:30Z', 'to': '2024-01-0...
19  {'from': '2024-01-01T09:00Z', 'to': '2024-01-0...
20  {'from': '2024-01-01T09:30Z', 'to': '2024-01-0...
21  {'from': '2024-01-01T10:00Z', 'to': '2024-01-0...
22  {'from': '2024-01-01T10:30Z', 'to': '2024-01-0...
23  {'from': '2024-01-01T11:00Z', 'to': '2024-01-0...
24  {'from': '2024-01-01T11:30Z', 'to': '2024-01-0...
25  {'from': '2024-01-01T12:00Z', 'to': '2024-01-0...
26  {'from': '2024-01-01T12:30Z', 'to': '2024-01-0...
27  {'from': '2024-01-01T13:00Z', 'to': '2024-01-0...
28  {'from': '2024-01-01T13:30Z', 'to': '2024-01-0...
29  {'from': '2024-01-01T14:00Z', 'to': '2024-01-0...
30  {'from': '2024-01-01T14:30Z', 'to': '2024-01-0...
31  {'from': '2024-01-01T15:00Z', 'to': '2024-01-0...
32  {'from': '2024-01-01T15:30Z', 'to': '2024-01-0...
33  {'from': '2024-01-01T16:00Z', 'to': '2024-01-0...
34  {'from': '2024-01-01T16:30Z', 'to': '2024-01-0...
35  {'from': '2024-01-01T17:00Z', 'to': '2024-01-0...
36  {'from': '2024-01-01T17:30Z', 'to': '2024-01-0...
37  {'from': '2024-01-01T18:00Z', 'to': '2024-01-0...
38  {'from': '2024-01-01T18:30Z', 'to': '2024-01-0...
39  {'from': '2024-01-01T19:00Z', 'to': '2024-01-0...
40  {'from': '2024-01-01T19:30Z', 'to': '2024-01-0...
41  {'from': '2024-01-01T20:00Z', 'to': '2024-01-0...
42  {'from': '2024-01-01T20:30Z', 'to': '2024-01-0...
43  {'from': '2024-01-01T21:00Z', 'to': '2024-01-0...
44  {'from': '2024-01-01T21:30Z', 'to': '2024-01-0...
45  {'from': '2024-01-01T22:00Z', 'to': '2024-01-0...
46  {'from': '2024-01-01T22:30Z', 'to': '2024-01-0...
47  {'from': '2024-01-01T23:00Z', 'to': '2024-01-0...
48  {'from': '2024-01-01T23:30Z', 'to': '2024-01-0...

In [25]:
df = pd.json_normalize(carbon_intensity_df['data'])

In [37]:
df

,from,to,intensity.forecast,intensity.actual,intensity.index
0,2023-12-31T23:30Z,2024-01-01T00:00Z,68,63,low
1,2024-01-01T00:00Z,2024-01-01T00:30Z,64,64,low
2,2024-01-01T00:30Z,2024-01-01T01:00Z,62,64,low
3,2024-01-01T01:00Z,2024-01-01T01:30Z,65,62,low
4,2024-01-01T01:30Z,2024-01-01T02:00Z,61,71,low
5,2024-01-01T02:00Z,2024-01-01T02:30Z,61,66,low
6,2024-01-01T02:30Z,2024-01-01T03:00Z,67,67,low
7,2024-01-01T03:00Z,2024-01-01T03:30Z,63,64,low
8,2024-01-01T03:30Z,2024-01-01T04:00Z,64,60,low
9,2024-01-01T04:00Z,2024-01-01T04:30Z,67,57,low
10,2024-01-01T04:30Z,2024-01-01T05:00Z,60,57,low
11,2024-01-01T05:00Z,2024-01-01T05:30Z,62,60,low
12,2024-01-01T05:30Z,2024-01-01T06:00Z,55,59,low
13,2024-01-01T06:00Z,2024-01-01T06:30Z,58,62,low
14,2024-01-01T06:30Z,2024-01-01T07:00Z,58,60,low
15,2024-01-01T07:00Z,2024-01-01T07:30Z,50,60,low
16,2024-01-01T07:30Z,2024-01-01T08:00Z,60,52,low
17,2024-01-01T08:00Z,2024-01-01T08:30Z,60,47,low
18,2024-01-01T08:30Z,2024-01-01T09:00Z,54,46,low
19,2024-01-01T09:00Z,2024-01-01T09:30Z,39,48,low
20,2024-01-01T09:30Z,2024-01-01T10:00Z,43,50,low
21,2024-01-01T10:00Z,2024-01-01T10:30Z,44,54,low
22,2024-01-01T10:30Z,2024-01-01T11:00Z,47,62,low
23,2024-01-01T11:00Z,2024-01-01T11:30Z,49,71,low
24,2024-01-01T11:30Z,2024-01-01T12:00Z,59,82,low
25,2024-01-01T12:00Z,2024-01-01T12:30Z,78,91,low
26,2024-01-01T12:30Z,2024-01-01T13:00Z,81,101,low
27,2024-01-01T13:00Z,2024-01-01T13:30Z,113,110,moderate
28,2024-01-01T13:30Z,2024-01-01T14:00Z,121,113,moderate
29,2024-01-01T14:00Z,2024-01-01T14:30Z,123,116,moderate
30,2024-01-01T14:30Z,2024-01-01T15:00Z,124,110,moderate
31,2024-01-01T15:00Z,2024-01-01T15:30Z,125,115,moderate
32,2024-01-01T15:30Z,2024-01-01T16:00Z,136,115,moderate
33,2024-01-01T16:00Z,2024-01-01T16:30Z,121,115,moderate
34,2024-01-01T16:30Z,2024-01-01T17:00Z,122,113,moderate
35,2024-01-01T17:00Z,2024-01-01T17:30Z,114,108,low
36,2024-01-01T17:30Z,2024-01-01T18:00Z,104,103,low
37,2024-01-01T18:00Z,2024-01-01T18:30Z,89,93,low
38,2024-01-01T18:30Z,2024-01-01T19:00Z,82,82,low
39,2024-01-01T19:00Z,2024-01-01T19:30Z,77,70,low
40,2024-01-01T19:30Z,2024-01-01T20:00Z,69,61,low
41,2024-01-01T20:00Z,2024-01-01T20:30Z,66,50,low
42,2024-01-01T20:30Z,2024-01-01T21:00Z,60,44,low
43,2024-01-01T21:00Z,2024-01-01T21:30Z,44,41,low
44,2024-01-01T21:30Z,2024-01-01T22:00Z,42,42,low
45,2024-01-01T22:00Z,2024-01-01T22:30Z,40,46,low
46,2024-01-01T22:30Z,2024-01-01T23:00Z,39,49,low
47,2024-01-01T23:00Z,2024-01-01T23:30Z,46,50,low
48,2024-01-01T23:30Z,2024-01-02T00:00Z,40,50,low

# Data Preprocessing

In [32]:
df.shape

(49, 5)

In [35]:
df.isnull().sum()

from                  0
to                    0
intensity.forecast    0
intensity.actual      0
intensity.index       0
dtype: int64

In [36]:
df.dtypes

from                  object
to                    object
intensity.forecast     int64
intensity.actual       int64
intensity.index       object
dtype: object