In [1]:
import pandas as pd
import requests
url = "https://data.elexon.co.uk/bmrs/api/v1/generation/actual/per-type?from=2025-01-01&to=2025-12-31&settlementPeriodFrom=1&settlementPeriodTo=50&format=json"

response = requests.get(url)
json_data = response.json()

#df = pd.read_json(url)
df = pd.json_normalize(
    json_data['data'],
    record_path='data',
    meta=['startTime', 'settlementPeriod']
)

In [3]:
df

,businessType,psrType,quantity,startTime,settlementPeriod
0,Production,Biomass,1517,2025-01-01T00:00:00Z,1
1,Production,Fossil Gas,3716,2025-01-01T00:00:00Z,1
2,Production,Fossil Hard coal,0,2025-01-01T00:00:00Z,1
3,Production,Fossil Oil,0,2025-01-01T00:00:00Z,1
4,Production,Hydro Pumped Storage,187,2025-01-01T00:00:00Z,1
...,...,...,...,...,...
4010,Production,Nuclear,4084,2025-12-31T00:00:00Z,1
4011,Production,Other,620,2025-12-31T00:00:00Z,1
4012,Solar generation,Solar,946,2025-12-31T00:00:00Z,1
4013,Wind generation,Wind Offshore,8196,2025-12-31T00:00:00Z,1
4014,Wind generation,Wind Onshore,5186,2025-12-31T00:00:00Z,1

In [7]:
df[df['settlementPeriod'] == 2]

Empty DataFrame
Columns: [businessType, psrType, quantity, startTime, settlementPeriod]
Index: []

In [ ]:
df['psrType'].unique()

In [ ]:
df['StartTime'] = pd.to_datetime(df['startTime']).dt.tz_localize(None)

In [ ]:
df[df['settlementPeriod'] == 2]

In [ ]:
df[(df['SettlementPeriod'] > 1) & (df['SettlementDate'] == '2025-01-01') & (df['PsrType'] == 'Biomass')]

In [ ]:
df_pivot = df.pivot_table(
    index='StartTime',
    columns='PsrType',
    values='Quantity',
    aggfunc='sum'
)

In [ ]:
df_pivot

In [ ]:
df_pivot['TotalOutput(MW)'] = df_pivot.sum(axis=1)